### ISSUE TITLE
Compatibility issue with MATLAB function 'mexSetTrapFlag' in 'tprod_mex.c' file.

### ISSUE THREAD

**Issue by kimukook** [ProbabilisticNumerics/entropy-search#4]
Thanks for providing this fabulous code. However, I am countering one issue resulted from MATLAB version R2018. When I tried to run the file ``ExampleSetup.m``, it showed the error that 'mexSetTrapFlag' function has been removed since MATLAB R2018, which is called in c-file 'tprod_mex.c' in line 332 and 438. MATLAB pages told me that the function 'mexSetTrapFlag' can be replaced by 'mexCallMATLABWithTrap' which is more flexible. But I am not sure how to edit this change. Is it possible if this problem could be fixed? Thank you so much!

**Comment by philipphennig** [comment]
Dear Muhan,

thanks for bringing this up. It sounds like this problem is caused by the external tprod library (the version we have in the repo might be too old now). 

Could you try updating to the most recent version [1] and let us know whether this fixes it for you? (you can probably just replace that library for the ./matlab/ext/tprod folder in our repo).

Thanks in advance, and best wishes,

Philipp


[1] https://de.mathworks.com/matlabcentral/fileexchange/16275-tprod-arbitary-tensor-products-between-n-d-arrays

**Comment by kimukook** [comment]
Dear Philip,
Thank you so much for your message. I tried to update the ```tprod``` library but the link referred above leads me to the same code as used in this repo. Searched online for a while but didn't find any available updated code of ```tprod``` library. I will keep an eye on this issue in future if one day get lucky. Just wanna thank you for your time and help :)
